name: noisling

services:
  app:
    build: .
    ports:
      - "1994:1994"
    environment:
      - DATABASE_PATH=/app/server/data/noisling.sqlite
      - MUSIC_DIR=/music
      - PORT=1994
      - COMPOSE_PROJECT_NAME=noisling
    volumes:
      - /mnt/data/music:/music:ro
      - sqlite-data:/app/server/data
      - covers:/app/server/covers
      - .:/repo
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  sqlite-data:
  covers:
